### ISSUE TITLE
[Event Page] Add event description component.

### ISSUE THREAD

**Issue by iiAbady** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#20]
**Task title**
Add event description component.

**Task description**
Add event description component with title and description.

**Subtasks**

- [ ] Add title ("Event Descripton")
- [ ] Add description

**Screenshots**
![Image](https://user-images.githubusercontent.com/29796196/227807175-ea8cb705-5536-47a2-8016-32dcab5a5be2.png)

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1663-2885&t=T4zHEMAENyzMmQGs-4

**Comment by sulmi24** [comment]
Hi @iiAbady
Thank you for assigning me the task! I'm excited to work on it and will make sure to complete each subtask to the best of my ability. I'll also make sure to update the task status as I complete each subtask, so we can keep track of progress.
