### ISSUE TITLE
[Event Page] Add attendees component.

### ISSUE THREAD

**Issue by iiAbady** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#22]
**Task title**
Add attendees component.

**Task description**
Add attendees component with their respective images and names as rounded cards.

**Subtasks**

- [x] Add single attendee component
- [x] Add attendees component

**Screenshots**

![Image](https://user-images.githubusercontent.com/29796196/227807118-21688eef-0550-4678-9f73-c79a20f10a76.png)

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1663-2885&t=T4zHEMAENyzMmQGs-4

**Comment by sulmi24** [comment]
Hi @iiAbady
Thank you for assigning me the task! I'm excited to work on it and will make sure to complete each subtask to the best of my ability. I'll also make sure to update the task status as I complete each subtask, so we can keep track of progress.
