### ISSUE TITLE
[Event Creation] add header component.

### ISSUE THREAD

**Issue by iiAbady** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#33]
**Task title**
add header component.

**Task description**
add header component which includes the location of the to-be-created-event.

**Screenshots**

![Image](https://user-images.githubusercontent.com/29796196/228632225-01137ef8-e039-438a-a9be-631396eb0c82.png)

**Link to the component on Figma**
https://www.figma.com/file/IEhYhDLnrHmUuYercEZUjA/Pebble-work?node-id=1663-2859&t=8okuRNWsC9ARYrtN-4

**Comment by sulmi24** [comment]
Thank you for creating issue **#33**, 
which requests the addition of a header component to the event creation page.
