### ISSUE TITLE
[Develop Edit Profile Page] Save user interests

### ISSUE THREAD

**Issue by SufyanCS** [202212-GIZ-YE-FEW/Web_Wizards_Pebble#81]
**Task description**
this feature allows users to select their preferred interests from a list of options. By doing so, the platform can tailor its content or recommendations based on the user's preferences, providing a more personalized experience.

**Screenshots**
![image](https://user-images.githubusercontent.com/119085953/231067465-cdbab685-e859-43c0-b0d4-2f3709617d6c.png)

**Comment by iiAbady** [comment]
This is closed by #126
